name: trek

services:

  # trek-postgres
  trek-postgres:
    image: postgres:alpine
    container_name: trek-postgres
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
  
  # trek-server
  server:
    container_name: trek-server
    build:
      context: ./trek-server
      dockerfile: Dockerfile
    restart: always
    ports:
      - "localhost:8080:8080"
    volumes:
      - /etc/localtime:/etc/localtime:ro  # sync time
      - ./trek-server/assets:/app/assets  # build dir

    depends_on:
      - trek-postgres
    environment:
      - GIN_MODE=release
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_SERVER=trek-postgres
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DB=${POSTGRES_DB}
      - ACCESS_TOKEN_SECRET=${ACCESS_TOKEN_SECRET}
      - ACCESS_TOKEN_LIFESPAN=${ACCESS_TOKEN_LIFESPAN}
      - TRACKER_TOKEN_SECRET=${TRACKER_TOKEN_SECRET}
      - SUPERUSER_USERNAME=${SUPERUSER_USERNAME}
      - SUPERUSER_PASSWORD=${SUPERUSER_PASSWORD}

volumes:
  postgres_data:
